/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import entidades.Produto_fornecedor;
import entidades.Fornecedor;
import entidades.Produto;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.Banco;

/**
 *
 * @author brunn
 */
public class CadastroProduto extends javax.swing.JDialog {
    private Produto produto;
    private List<Produto_fornecedor> fornecedores;
    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        jbutaonovo.setEnabled(false);
        this.produto = null;
        this.fornecedores = new ArrayList();
        jcodigo.requestFocus();
    }
    
    public CadastroProduto(java.awt.Frame parent, boolean modal, Produto produto) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.produto = produto;
        jbutaonovo.setVisible(false);
        jcodigo.setText(produto.getCodigobarras());
        jdescricao.setText(produto.getDescricao());
        jestoque.setText(produto.getEstoque()+"");
        jpreco.setText(produto.getPreco()+"");
        jmarca.setText(produto.getMarca());
        this.fornecedores = produto.getFornecedor();
        DefaultTableModel modelo = (DefaultTableModel) jtabela_fornecedor.getModel();
        String[] linha = new String[3];
        for (Produto_fornecedor fornecedor : produto.getFornecedor()){
            linha[0] = fornecedor.getFornecedor().getId()+"";
            linha[1] = fornecedor.getFornecedor().getCnpj();
            linha[2] = fornecedor.getFornecedor().getRazao();
            modelo.addRow(linha);
        }
        
        jcodigo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jdescricao = new javax.swing.JTextField();
        jpreco = new javax.swing.JTextField();
        jestoque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jmarca = new javax.swing.JTextField();
        jbutaosalvar = new javax.swing.JButton();
        jbutaonovo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabela_fornecedor = new javax.swing.JTable();
        jbutaobuscar = new javax.swing.JButton();
        jbutaoexcluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CÓDIGO DE BARRAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PREÇO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ESTOQUE");

        jdescricao.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jdescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdescricaoKeyPressed(evt);
            }
        });

        jpreco.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jpreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jprecoKeyPressed(evt);
            }
        });

        jestoque.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jestoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jestoqueKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DESCRIÇÃO");

        jcodigo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcodigoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MARCA");

        jmarca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmarca)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jestoque, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jestoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbutaosalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar.png"))); // NOI18N
        jbutaosalvar.setText("SALVAR");
        jbutaosalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaosalvarActionPerformed(evt);
            }
        });

        jbutaonovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Add.png"))); // NOI18N
        jbutaonovo.setText("NOVO");
        jbutaonovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaonovoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORNECEDORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jtabela_fornecedor.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jtabela_fornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Razão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabela_fornecedor.setRowHeight(25);
        jtabela_fornecedor.getTableHeader().setReorderingAllowed(false);
        jtabela_fornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtabela_fornecedorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtabela_fornecedor);
        if (jtabela_fornecedor.getColumnModel().getColumnCount() > 0) {
            jtabela_fornecedor.getColumnModel().getColumn(0).setResizable(false);
            jtabela_fornecedor.getColumnModel().getColumn(0).setPreferredWidth(30);
            jtabela_fornecedor.getColumnModel().getColumn(1).setResizable(false);
            jtabela_fornecedor.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jbutaobuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jbutaobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaobuscarActionPerformed(evt);
            }
        });

        jbutaoexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Lixeira2.png"))); // NOI18N
        jbutaoexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutaoexcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbutaoexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbutaobuscar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbutaoexcluir)
                    .addComponent(jbutaobuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cadastro de Produto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(213, 213, 213))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbutaonovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbutaosalvar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutaosalvar)
                    .addComponent(jbutaonovo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutaosalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaosalvarActionPerformed
        this.salvar();
    }//GEN-LAST:event_jbutaosalvarActionPerformed

    private void jbutaonovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaonovoActionPerformed
        this.novo();
    }//GEN-LAST:event_jbutaonovoActionPerformed

    private void jbutaobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaobuscarActionPerformed
        this.buscaFornecedor();
    }//GEN-LAST:event_jbutaobuscarActionPerformed

    private void jcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcodigoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jdescricao.requestFocus();
        }
    }//GEN-LAST:event_jcodigoKeyPressed

    private void jdescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdescricaoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jmarca.requestFocus();
        }
    }//GEN-LAST:event_jdescricaoKeyPressed

    private void jprecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprecoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jestoque.requestFocus();
        }
    }//GEN-LAST:event_jprecoKeyPressed

    private void jestoqueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jestoqueKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.jtabela_fornecedor.requestFocus();
        }
        if(evt.getKeyCode() == KeyEvent.VK_F3){
            this.buscaFornecedor();
        }
    }//GEN-LAST:event_jestoqueKeyPressed

    private void jtabela_fornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtabela_fornecedorKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DELETE){
            this.excluir();
        }
        if(evt.getKeyCode() == KeyEvent.VK_F3){
            this.buscaFornecedor();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            this.salvar();
        }
    }//GEN-LAST:event_jtabela_fornecedorKeyPressed

    private void jbutaoexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutaoexcluirActionPerformed
        this.excluir();
    }//GEN-LAST:event_jbutaoexcluirActionPerformed
    
    private void novo(){
        jbutaosalvar.setEnabled(true);
        jbutaonovo.setEnabled(false);
        jcodigo.setText("");
        jdescricao.setText("");
        jpreco.setText("");
        jestoque.setText("");
        jmarca.setText("");
        this.produto = null;
        this.fornecedores = new ArrayList();        
        jbutaosalvar.setEnabled(true);
        jbutaoexcluir.setEnabled(true);
        jbutaobuscar.setEnabled(true);
        jbutaonovo.setEnabled(false);
        DefaultTableModel modelo = (DefaultTableModel) jtabela_fornecedor.getModel();
        int tam = modelo.getRowCount();
        for(int i=0;i<tam;i++){
            modelo.removeRow(0);
        }
        jcodigo.requestFocus();
    }
    private void excluir(){
        int v = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse Fornecedor?", "EXCLUIR FORNECEDOR", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(v == JOptionPane.YES_OPTION){
            int i = jtabela_fornecedor.getSelectedRow();
            this.fornecedores.remove(i);
            DefaultTableModel modelo = (DefaultTableModel) jtabela_fornecedor.getModel();
            modelo.removeRow(i);
        }
    }
    private void buscaFornecedor(){
        Fornecedor fornecedor = new Fornecedor();
        BuscaFornecedor busca = new BuscaFornecedor(null, true, fornecedor);
        busca.setVisible(true);
        if(fornecedor.getId() != 0){
            if(!verificarFornecedor(fornecedor.getId())){
                DefaultTableModel modelo = (DefaultTableModel) jtabela_fornecedor.getModel();
                Produto_fornecedor profor = new Produto_fornecedor();
                profor.setFornecedor(fornecedor);
                profor.setProduto(produto);
                this.fornecedores.add(profor);
                String[] linha = new String[2];
                linha[0] = fornecedor.getId()+"";
                linha[1] = fornecedor.getRazao();
                modelo.addRow(linha);
            }
        }
        jtabela_fornecedor.requestFocus();
    }
    private boolean verificarFornecedor(int id){
        for (Produto_fornecedor profor : this.fornecedores){
            if(profor.getFornecedor().getId() == id){
                return true;
            }
        }
        return false;
    }
    private void salvar(){
        if(this.produto == null){
            this.produto = new Produto();
            produto.setCodigobarras(jcodigo.getText());
            produto.setDescricao(jdescricao.getText());
            produto.setEstoque(Integer.parseInt(jestoque.getText()));
            produto.setPreco(Double.parseDouble(jpreco.getText()));
            produto.setMarca(jmarca.getText());
            produto.setStatus(Produto.ATIVO);
            produto.setFornecedor(this.fornecedores);
            Banco.getBanco().cadastrar(this.produto);
            JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso!");
            jbutaosalvar.setEnabled(false);
            jbutaoexcluir.setEnabled(false);
            jbutaobuscar.setEnabled(false);
            jbutaonovo.setEnabled(true);
            this.produto = null;
        }else{
            produto.setCodigobarras(jcodigo.getText());
            produto.setDescricao(jdescricao.getText());
            produto.setEstoque(Double.parseDouble(jestoque.getText()));
            produto.setPreco(Double.parseDouble(jpreco.getText()));
            produto.setMarca(jmarca.getText());
            produto.setStatus(Produto.ATIVO);
            produto.setFornecedor(this.fornecedores);
            produto.setStatus(Produto.ATIVO);
            Banco.getBanco().editarProduto(this.produto);
            JOptionPane.showMessageDialog(null, "Produto alterado com sucesso!");
            this.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbutaobuscar;
    private javax.swing.JButton jbutaoexcluir;
    private javax.swing.JButton jbutaonovo;
    private javax.swing.JButton jbutaosalvar;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JTextField jdescricao;
    private javax.swing.JTextField jestoque;
    private javax.swing.JTextField jmarca;
    private javax.swing.JTextField jpreco;
    private javax.swing.JTable jtabela_fornecedor;
    // End of variables declaration//GEN-END:variables
}
