/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import entidades.Item;
import entidades.Venda;
import janelas.auxiliar.JCalendar;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.Banco;

/**
 *
 * @author brunn
 */
public class ConsultaVendas extends javax.swing.JDialog {
    
    private List<Venda> lista;
    
    /**
     * Creates new form ConsultaVendas
     */
    public ConsultaVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaVendas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaItens = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jdataInicial = new janelas.auxiliar.JCalendar(false);
        jdataFinal = new janelas.auxiliar.JCalendar(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setForeground(new java.awt.Color(0, 0, 204));
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Vendas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addComponent(jLabel1)
                .addContainerGap(389, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTabelaVendas.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "CLIENTE", "TOTAL", "VENDEDOR", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaVendas.setRowHeight(40);
        jTabelaVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabelaVendasMouseClicked(evt);
            }
        });
        jTabelaVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabelaVendasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaVendas);
        if (jTabelaVendas.getColumnModel().getColumnCount() > 0) {
            jTabelaVendas.getColumnModel().getColumn(0).setResizable(false);
            jTabelaVendas.getColumnModel().getColumn(1).setResizable(false);
            jTabelaVendas.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTabelaVendas.getColumnModel().getColumn(2).setResizable(false);
            jTabelaVendas.getColumnModel().getColumn(3).setResizable(false);
            jTabelaVendas.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jTabelaItens.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jTabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUTO", "PREÇO", "QUANTIDADE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabelaItens.setRowHeight(40);
        jScrollPane2.setViewportView(jTabelaItens);
        if (jTabelaItens.getColumnModel().getColumnCount() > 0) {
            jTabelaItens.getColumnModel().getColumn(0).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(0).setPreferredWidth(450);
            jTabelaItens.getColumnModel().getColumn(1).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTabelaItens.getColumnModel().getColumn(2).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTabelaItens.getColumnModel().getColumn(3).setResizable(false);
            jTabelaItens.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busca de Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jdataInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jdataFinal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Data Inicial");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Data Final");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisa2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.buscarVenda();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabelaVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabelaVendasMouseClicked
        // TODO add your handling code here:
        this.addItens();
    }//GEN-LAST:event_jTabelaVendasMouseClicked

    private void jTabelaVendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabelaVendasKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            //int sel = jTabelaVendas.getSelectedRow();
            //if(sel >= 0){
                //this.produtoSelecionado(sel+1);
            //}else{
                //this.produtoSelecionado(0);
            //}
            //this.addItens();
        }if(evt.getKeyCode() == KeyEvent.VK_UP){
            //int sel = jTabelaPesquisa.getSelectedRow();
            //this.produtoSelecionado(sel - 1);
            //this.addItens();
        }
    }//GEN-LAST:event_jTabelaVendasKeyPressed
    
    public void addItens(){
        Venda venda = this.lista.get(jTabelaVendas.getSelectedRow());
        
        DefaultTableModel modelo = (DefaultTableModel) jTabelaItens.getModel();
        int tam = modelo.getRowCount();
        for(int i=0;i<tam;i++){
            modelo.removeRow(0);
        }
        
        for (Item item : venda.getItens()){
            String[] linha = new String[7];
            linha[0] = item.getProduto().getDescricao();
            linha[1] = "R$ "+item.getPreco()+"".replace(".", ",");
            linha[2] = item.getQuantidade()+"";
            linha[3] = "R$ "+item.getTotal()+"".replace(".", ",");
            modelo.addRow(linha);
        }
        
    }//Fim addItens
    
    public void buscarVenda(){
        DefaultTableModel modelo = (DefaultTableModel) jTabelaVendas.getModel();
        int tam = modelo.getRowCount();
        for(int i=0;i<tam;i++){
            modelo.removeRow(0);
        }
        
        String dataInicial = ((JCalendar)jdataInicial).getText();
        String dataFinal = ((JCalendar)jdataFinal).getText();
        
        try {
            if(dataInicial.length() > 0 && dataFinal.length() > 0){
                java.text.SimpleDateFormat formatodata = new java.text.SimpleDateFormat("dd/MM/yyyy"); 
                
                String[] inicio = dataInicial.split("/");
                String[] fim = dataFinal.split("/");
                
                this.lista = Banco.getBanco().consultaVendas(inicio[2]+"-"+inicio[1]+"-"+inicio[0], fim[2]+"-"+fim[1]+"-"+fim[0]);

                for (Venda venda : lista) {
                    String[] linha = new String[7];
                    linha[0] = formatodata.format(venda.getData());
                    linha[1] = venda.getCliente().getNome();
                    linha[2] = "R$ "+venda.getTotal()+"".replace(".", ",");
                    linha[3] = venda.getUsuario().getNome();
                    if(venda.getStatus()==Venda.DESATIVADO){
                        linha[4] = "Ok";
                    }else{
                        linha[4] = "Pendente";
                    }
                    modelo.addRow(linha);
                }

                //jInicio.setText(dataInicial);
                //jFim.setText(dataFinal);
            }else{
                JOptionPane.showMessageDialog(null, "Data Inválida!");
            }
        } catch (Exception ex) {
            Logger.getLogger(ConsultaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaItens;
    private javax.swing.JTable jTabelaVendas;
    private javax.swing.JComboBox<String> jdataFinal;
    private javax.swing.JComboBox<String> jdataInicial;
    // End of variables declaration//GEN-END:variables
}
