/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import entidades.Produto;
import janelas.auxiliar.BarraBusca;
import janelas.auxiliar.BarraEntrada;
import janelas.auxiliar.Iniciando;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTable;
import persistencia.ProcessoProduto;

/**
 *
 * @author Bruno
 */
public class JanelaBarra extends javax.swing.JFrame {
    
    private JFrame janela;
    
    /**
     * Creates new form JanelaBarra
     */
    public JanelaBarra(JFrame janela, String login, String senha) {
        initComponents();
        Image icone = Toolkit.getDefaultToolkit().getImage("logo.png");
        this.setIconImage(icone);
        this.setLocationRelativeTo(null);
        
        this.janela = janela;
        jbarra.setValue(10);
        Iniciando iniciando = new Iniciando(this.janela,login, senha);
        //iniciando.start();
        
        BarraEntrada barra = new BarraEntrada(this,jbarra,iniciando);
        barra.start();
        
    }
    
    public JanelaBarra(JFrame janela, JTable tabela, String chave,List<Produto> produto){
        initComponents();
        Image icone = Toolkit.getDefaultToolkit().getImage("logo.png");
        this.setIconImage(icone);
        this.setLocationRelativeTo(null);
        this.janela = janela;
        
        //ProcessoProduto processo = new ProcessoProduto(tabela, chave, produto);
        //jbarra.setValue(10);
        jtexto.setText("Buscando Produtos...");
        //BarraBusca barra = new BarraBusca(this, jbarra, processo);
        //barra.start();
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtexto = new javax.swing.JLabel();
        jbarra = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtexto.setText("Iniciando o Sistema...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtexto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbarra, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jbarra;
    private javax.swing.JLabel jtexto;
    // End of variables declaration//GEN-END:variables
}
