/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import janelas.auxiliar.BarraBusca;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import persistencia.ProcessoProduto;

/**
 *
 * @author brunn
 */
public class JanelaBarraBusca extends javax.swing.JDialog {
    private JFrame janela;
    /**
     * Creates new form JanelaBarraBusca
     */
    public JanelaBarraBusca(JFrame janela, JTable tabela, String chave,List lista, boolean minimo) {
        super(janela, true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.janela = janela;

        ProcessoProduto processo = new ProcessoProduto(tabela, chave, lista, minimo);
        jbarra.setValue(10);
        jtexto.setText("Buscando produtos...");
        BarraBusca barra = new BarraBusca(this, jbarra, jtexto, processo);
        barra.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbarra = new javax.swing.JProgressBar();
        jtexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jtexto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtexto.setText("Buscando produtos...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtexto)
                        .addGap(0, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jbarra;
    private javax.swing.JLabel jtexto;
    // End of variables declaration//GEN-END:variables
}
